# Generated by Django 2.0.6 on 2018-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_viz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='word',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
