# Generated by Django 2.0.6 on 2018-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_viz', '0002_post_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
